# Generated by Django 5.2.15 on 2026-06-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='reference',
            field=models.CharField(blank=True, max_length=120, verbose_name='Receipt / invoice no.'),
        ),
        migrations.AddField(
            model_name='expense',
            name='supplier_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Supplier address'),
        ),
        migrations.AddField(
            model_name='expense',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=160, verbose_name='Supplier / vendor'),
        ),
        migrations.AddField(
            model_name='expense',
            name='supplier_tin',
            field=models.CharField(blank=True, max_length=40, verbose_name='Supplier TIN'),
        ),
    ]
