# Generated by Django 5.2.15 on 2026-06-27 04:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0002_expense_reference_expense_supplier_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Hourly rate (₱)'),
        ),
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('photo_in', models.ImageField(blank=True, null=True, upload_to='timelogs/%Y/%m/')),
                ('photo_out', models.ImageField(blank=True, null=True, upload_to='timelogs/%Y/%m/')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelogs', to='spa.staffprofile')),
            ],
            options={
                'ordering': ['-clock_in'],
            },
        ),
        migrations.CreateModel(
            name='PayrollMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_marks', to='spa.staffprofile')),
            ],
            options={
                'unique_together': {('staff', 'week_start')},
            },
        ),
    ]
