# Generated by Django 5.2.15 on 2026-06-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0003_staffprofile_hourly_rate_timelog_payrollmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='service',
            name='group',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='service',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='variant',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
