"""
Django settings for oasis project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load a local ".env" file (KEY=VALUE per line) if present, so the office
# install can point at a cloud database (e.g. Supabase) without setting
# Windows environment variables. Real env vars always win over the file.
_env_file = BASE_DIR / '.env'
if _env_file.exists():
    for _line in _env_file.read_text(encoding='utf-8-sig').splitlines():
        _line = _line.strip()
        if _line and not _line.startswith('#') and '=' in _line:
            _k, _v = _line.split('=', 1)
            os.environ.setdefault(_k.strip(), _v.strip().strip('"').strip("'"))

# Settings read from environment variables when deployed (e.g. Vercel),
# falling back to local-friendly defaults so the office install just works.

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    'django-insecure-wh@jyd#uw+sf_u#149o_gm_re-x(m19z@!r_#5o*d$ttnz2tg=',
)

# DEBUG is on locally; set DEBUG=False in the hosting environment.
DEBUG = os.environ.get("DEBUG", "True").lower() in ("1", "true", "yes")

# Comma-separated hostnames in the env; defaults to "any" for the office LAN.
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "*").split(",")

# Trust the HTTPS origin(s) of the host (needed for forms/login on Vercel).
CSRF_TRUSTED_ORIGINS = [
    o for o in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",") if o
]
# Convenience: Vercel sets VERCEL_URL to the deployment's hostname.
_vercel_url = os.environ.get("VERCEL_URL")
if _vercel_url:
    ALLOWED_HOSTS.append(_vercel_url)
    CSRF_TRUSTED_ORIGINS.append(f"https://{_vercel_url}")
    CSRF_TRUSTED_ORIGINS.append("https://*.vercel.app")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'spa',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves static files (CSS, logo) in production without a
    # separate web server. Harmless locally.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'oasis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'spa.context_processors.oasis',
            ],
        },
    },
]

WSGI_APPLICATION = 'oasis.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Local: a single SQLite file. Deployed: a managed Postgres via a connection
# URL (DATABASE_URL, or POSTGRES_URL which Vercel Postgres provides).
_db_url = os.environ.get("DATABASE_URL") or os.environ.get("POSTGRES_URL")
if _db_url:
    import dj_database_url
    DATABASES = {
        "default": dj_database_url.parse(_db_url, conn_max_age=600, ssl_require=True)
    }
    # Make it safe behind a connection pooler (Supabase Supavisor / PgBouncer
    # transaction mode): disable psycopg3 prepared statements + server cursors.
    DATABASES["default"].setdefault("OPTIONS", {})
    DATABASES["default"]["OPTIONS"]["prepare_threshold"] = None
    DISABLE_SERVER_SIDE_CURSORS = True
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# collectstatic gathers files under .../staticfiles_build/static so that, on
# Vercel, they're served from the /static/ URL prefix (WhiteNoise at runtime).
STATIC_ROOT = BASE_DIR / 'staticfiles_build' / 'static'
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"
    },
}

# Uploaded files (payment screenshots, expense receipts).
# NOTE: on serverless hosts (Vercel) the disk is temporary, so uploads do not
# persist there — fine for the public booking page (no uploads), not for real
# payment/receipt records, which stay on the local office install.
MEDIA_URL = 'media/'
MEDIA_ROOT = os.environ.get("MEDIA_ROOT", str(BASE_DIR / 'media'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication redirects
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# ---------------------------------------------------------------------------
# Oasis on the Go Spa — business settings (edit these to suit operations)
# ---------------------------------------------------------------------------
OASIS = {
    'COMPANY_NAME': 'Oasis on the Go Spa',
    'CURRENCY_SYMBOL': '₱',          # PHP peso
    'OPEN_TIME': '14:00',                  # 2:00 PM
    'CLOSE_TIME': '00:00',                 # 12:00 midnight
    'SLOT_MINUTES': 60,                    # length of each bookable time slot
    'RECEIPT_MODEL': 'claude-haiku-4-5',   # Claude model for AI receipt auto-fill (cheap + fast)
    'PAYMENT_METHODS': ['Cash', 'GCash', 'QRPH', 'Credit Card'],
    'BOOKING_CHANNELS': ['Facebook', 'Phone', 'Walk-in', 'Website'],
    'EXPENSE_CATEGORIES': [
        'Supplies', 'Utilities', 'Rent', 'Salaries', 'Transport',
        'Marketing', 'Maintenance', 'Miscellaneous',
    ],
}
